- question: Що включає в себе поняття "інформаційна гігієна"?
  answers:
   - Вплив на організм людини та суспільне здоров'я інформаційних потоків, що надходять до людини.
  - Система, призначена для одержання, обробки, зберігання, відображення та/або реєстрації даних
   - Нову історичну фазу розвитку суспільства
- question: Несвідома неправда, коли вас не хотіли вводити в оману. Просто помилка.
 answers:
   - Disinformation
   - Misinformation
   - Malinformation
